version: '3.8'

services:
  mongo:
    image: mongo:4.4
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - es-data:/usr/share/elasticsearch/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: unified-go-backend
    depends_on:
      - mongo
      - redis
      - elasticsearch
    ports:
      - "8080:8080"
    environment:
      MONGO_URI: mongodb://mongo:27017/mdmdb
      REDIS_ADDR: redis:6379
      SMTP_HOST: smtp.mailtrap.io
      SMTP_PORT: 587
      SMTP_USER: your_mailtrap_user
      SMTP_PASSWORD: your_mailtrap_password
      JWT_SECRET: your_jwt_secret
      ELASTICSEARCH_URL: http://elasticsearch:9200
    volumes:
      - .:/app

volumes:
  mongo-data:
  redis-data:
  es-data:
