basePath: /
host: localhost:8080
info:
  contact:
    email: manvfx@gmail.com
    name: API Support
  description: This is a sample server for a Unified Go Backend.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Unified Go Backend
  version: "1.0"
paths: {}
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
